'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Alphabet_Soup.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property A() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("A", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Achievements() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Achievements", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property all() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("all", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ant() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ant", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Apple() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Apple", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property B() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Back_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Back_Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Bat() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Bat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property bensound_littleidea() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("bensound_littleidea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BlackSoundIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlackSoundIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BlueFish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueFish", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BlueSoundIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueSoundIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Book() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Book", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property C() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Car() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Car", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Cat() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Cat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Check_mark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Check_mark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChestClosed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChestClosed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChestOpen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChestOpen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Correct_Answer() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Correct_Answer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cover_alphabetsketch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cover_alphabetsketch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cover_findme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cover_findme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cover_soundoff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cover_soundoff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cover_tapit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cover_tapit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cover_whatami() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cover_whatami", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property D() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Dog() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Dog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Dog2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Dog2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property E() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Eat() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Eat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Erasor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Erasor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property F() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("F", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Fat() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Fat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Flower() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Flower", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property G() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("G", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Game() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Game", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Grade_Book_Cover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grade_Book_Cover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Grade_Book_Spine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grade_Book_Spine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property H() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Hat() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Hat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property homeIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("homeIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property House() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("House", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property I() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ice() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Instruction_Drag_Letter_Toybox() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Instruction_Drag_Letter_Toybox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Instruction_Drag_Letter_Word() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Instruction_Drag_Letter_Word", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Instruction_Tap_Speaker() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Instruction_Tap_Speaker", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Instruction_Tap_Speaker_Type_Keyboard() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Instruction_Tap_Speaker_Type_Keyboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Instruction_Trace_Outline() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Instruction_Trace_Outline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Instruction_Try_Again() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Instruction_Try_Again", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Instruction_Try_Again_Short() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Instruction_Try_Again_Short", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Instruction_Type_Keyboard() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Instruction_Type_Keyboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property J() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("J", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property K() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property L() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LetterStyle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LetterStyle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property LondrinaOutline_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("LondrinaOutline_Regular", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property M() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("M", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Main_Screen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Main_Screen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Mouse() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Mouse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property N() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("N", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Next_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Next_Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Note() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Note", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property O() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("O", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property P() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("P", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Page_Screen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Page_Screen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PaintSplotch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PaintSplotch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Q() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Q", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Question_Mark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question_Mark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property R() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property S() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("S", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property smiley() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smiley", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SpeakerIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpeakerIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spine_alphabetsketch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spine_alphabetsketch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spine_findme() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spine_findme", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spine_soundoff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spine_soundoff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spine_tapit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spine_tapit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spine_whatami() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spine_whatami", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property T() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("T", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Telephone() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Telephone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Title_Alphabet_Sketch() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Title_Alphabet_Sketch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Title_Find_Me() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Title_Find_Me", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Title_Grade_Book() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Title_Grade_Book", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Title_Sound_Off() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Title_Sound_Off", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Title_What_Am_I() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Title_What_Am_I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property U() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("U", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UserAdd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UserAdd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UserRemove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UserRemove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property V() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("V", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Violin() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Violin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property W() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("W", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Watermelon() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Watermelon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Apple_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Apple_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Apple_Non_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Apple_Non_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Book_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Book_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Book_Non_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Book_Non_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Cat_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Cat_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Cat_Non_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Cat_Non_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Dog_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Dog_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Dog_Non_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Dog_Non_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Flower_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Flower_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Flower_Non_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Flower_Non_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_House_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_House_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_House_Non_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_House_Non_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Mouse_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Mouse_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Mouse_Non_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Mouse_Non_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Telephone_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Telephone_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Telephone_Non_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Telephone_Non_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Violin_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Violin_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Violin_Non_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Violin_Non_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Watermelon_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Watermelon_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property What_Am_I_Watermelon_Non_Coloured() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("What_Am_I_Watermelon_Non_Coloured", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property X() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("X", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x_mark_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x_mark_large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Y() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Y", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YellowFish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowFish", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Z() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Z", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
